# Display.
title: "The Tidynomicon"
subtitle: "A Brief Introduction to R for Python Programmers"
editor: "Greg Wilson"
copyrightyear: "2019"
repo: "https://github.com/gvwilson/tidynomicon/"
website: "https://gvwilson.github.io/tidynomicon/"
email: "gvwilson@third-bit.com"
isbn: "000-0-0000000-0-0"

# Order for Table of Contents.
toc:
  lessons:
  - basics
  - indexing
  - control
  - tidyverse
  - cleanup
  - nse
  - errors
  - oop
  - debt
  - projects
  - testing
  - shiny
  - reticulate
  bib:
  - bib
  extras:
  - license
  - conduct
  - citation
  - contributing
  - objectives
  - keypoints
  - gloss

include:
- "_en/images/*.*"
# Tell Jekyll that "en" is a collection (whose files are found in "_en").  This
# is what allows us to loop over files in various inclusions.  We use "en" to
# indicate English, and can use other two-letter codes for other languages.
collections:
  en:
    output: true
    permalink: /:collection/:title.html

# Specify the use of the "lesson" template for elements of the "en" collection.
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "lesson"

# Translations keyed by language.  This lookup table allows us to put the right
# titles on inclusion blocks in various languages.
translations:
  en:
    generated: "Last generated"
    questions: "Questions"
    keypoints: "Key Points"
    lulu: "Buy on Lulu"

# Standard Jekyll settings.
repository: <USERNAME>/<PROJECT>
highlighter: rouge
plugins:
- "jekyll-redirect-from"
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- DESIGN.md
- LICENSE.md
- Makefile
- README.md
- bin
- etc
- misc
- node_modules
- requirements.txt
- site.mk
- site.yml
- src
- tex
