title: "The Tidynomicon"
author: "Greg Wilson"

lessons:
- /beginnings/
- /tidyverse/
- /cleanup/
- /debt/
- /oop/
- /projects/

extras:
- url: "/license/"
  title: "License"
- url: "/conduct/"
  title: "Code of Conduct"
- url: "/citation/"
  title: "Citation"
- url: "/objectives/"
  title: "Learning Objectives"
- url: "/keypoints/"
  title: "Key Points"
- url: "/glossary/"
  title: "Glossary"

collections:
  en:
    output: true
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "default"

exclude:
- "*.Rmd"
- "*.Rproj"
- README.md
- bin
